export const _env = {
    API_KEY: process.env.API_KEY,
    API_URL: process.env.API_URL,
    CLIENT_HOST: process.env.CLIENT_HOST,
}

export const icons = [
    '',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/1.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/2.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/3.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/4.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/5.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/6.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/7.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/8.svg',
    '',
    '',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/11.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/12.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/13.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/14.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/15.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/16.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/17.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/18.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/19.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/20.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/21.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/22.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/23.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/24.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/25.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/26.svg',
    '',
    '',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/29.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/30.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/31.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/32.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/33.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/34.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/35.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/36.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/37.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/38.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/39.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/40.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/41.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/42.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/43.svg',
    'https://www.accuweather.com/assets/images/weather-icons/v2a/44.svg',
]